### ISSUE TITLE
Tab contents are inaccessible if JS is turned off

### ISSUE THREAD

**Issue by rouilj** [mayank99/tabs#1]
If a user has javascript turned off (or something breaks in the HTML web component), what should a
tabbed interface experience become?

I claim that the info in the tabs should be accessible even if javascript is disabled.
Currently, that does not seem to be the case (I had JS turned off when viewing https://www.mayank.co/blog/tabs). I would think the `hidden` tabpanels should be shown and the tablist should be hidden.

IIUC in the `connectedCallback`, you could remove a `hidden` property from the tablist.
Also you can identify the index of the tabpanel that is supposed to be shown from the tablist.
Then set the hidden attribute/property on the rest of the tabpanels.

Maybe default CSS like:
```
:not(the-tabs:defined) [role=tablist] { display: none; }
```
would work in place of `hidden` and reduce the work needed by JS?

Also to handle the case where javascript is disabled, maybe change the markup to:
```
<the-tabs>
	<div role='tablist'  hidden>
		<button role='tab' aria-selected='true'>…</button>
		<button role='tab'>…</button>
		<button role='tab'>…</button>
	</div>

        <noscript class="panelLabel">Panel HTML</noscript>
	<div role='tabpanel'>…</div>
	<noscript class="panelLabel">Panel CSS</noscript>
        <div role='tabpanel' hidden>…</div>
	<noscript class="panelLabel">Panel JS</noscript>
        <div role='tabpanel' hidden>…</div>
</the-tabs>
```
using `noscript` to label the tabpanels. (I'm not sure that class is valid on a `noscript` tag,
but you get the idea.)

Thoughts?

**Comment by mayank99** [comment]
Hey @rouilj, thanks for opening this issue.

I think the way the JS is written, it does not require you to hide the panels in your initial markup, so yes you can absolutely use `:defined` for progressive enhancement. I would not use `noscript`, as it's not super reliable for cases where JavaScript is not disabled but may not have loaded correctly. See https://www.kryogenix.org/code/browser/everyonehasjs.html

You could do something like this:

<details><summary>Code</summary>

```html
<the-tabs>
  <div role='tablist'>
	<button role='tab' aria-selected='true'>Apple</button>
	<button role='tab'>Banana</button>
	<button role='tab'>Kiwi</button>
  </div>

  <div role='tabpanel'>
    <h2>Apple</h2>
    Content
  </div>

  <div role='tabpanel'>
    <h2>Banana</h2>
    Content
  </div>

  <div role='tabpanel'>
    <h2>Kiwi</h2>
    Content
  </div>
</the-tabs>
```

```css
the-tabs:not(:defined) {
  [role=tablist] { display: none; }
}
the-tabs:defined {
  [role=tabpanel] h2 { display: none; }
}
```
</details> 

Note that this will cause layout shift for users who do have JS. You could optimize for JS-first using an animation. Something like this (not tested but you get the idea):

```css
@keyframes hide-after-delay {
  to { display: none; }
}
@keyframes show-after-delay {
  from { display: none; }
  to { display: block; }
}

the-tabs:defined {
  [role=tabpanel] h2 { display: none; }
}

the-tabs:not(:defined) {
  [role=tablist] {
    animation: hide-after-delay 1ms 5s;
  }
  [role=tabpanel] h2  {
    animation: show-after-delay 1ms 5s;
  }
}
```

Let me know if you think there are any changes needed in the component code.
